name: compressor_env
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pandas>=1.3
  - numpy>=1.20
  - matplotlib>=3.3
  - seaborn>=0.11
  - jupyter>=1.0
  - ipykernel>=6.0
  - pip
  - pip:
      - plotly>=5.0
      - thermo>=0.2
